---

# ------------------------------------------------------------------------------

  # Firewall settings
- name: POST | {{ application }} firewall settings
  become: true
  notify:
    - reload_daemon
    - restart_firewalld
  firewalld:
    permanent: yes
    state: enabled
    port: "{{ item }}"
  loop:
    - 4646-4648/tcp
    - 20000-32000/tcp
    - 4648/udp
  when: configure_firewalld
  tags: ["post"]

# ------------------------------------------------------------------------------

  # SELinux settings
- name: POST | SELinux permissive, logging actions that would be blocked
  become: true
  selinux:
    policy: targeted
    state: permissive
  when: configure_selinux
  tags: ["post"]

# ------------------------------------------------------------------------------

- name: POST | Start and enable {{ application }} unit
  become: true
  notify:
    - reload_daemon
  systemd:
    name: "{{ application }}"
    masked: no
    enabled: yes
    state: started
  tags: ["post"]

# ------------------------------------------------------------------------------

  # Run all handlers
- name: POST | Flush handlers
  meta: flush_handlers
  tags: ["post"]
