---

  # Check if file already downloaded
- name: check for application archive
  stat:
    path: "{{ path_temp }}/{{ package_name }}.zip"
  register: archive_status

- name: download application archive
  get_url:
    url: "{{ package_url }}"
    dest: "{{ path_temp }}"
    checksum: "sha256:{{ checksum_url }}"
    validate_certs: false
  register: download_status
  when: not archive_status['stat']['exists'] | bool
