---

- name: Check if folders already exist
  stat:
    path: "{{ item }}"
  register: folder_status
  loop:
  - "{{ path_settings }}/{{ application }}.d"
  - "{{ path_binaries }}"
  - "{{ path_packages }}/{{ application }}/{{ version }}"
  - "{{ path_systemd }}/{{ application }}.service.d"
  - "{{ path_storage }}/{{ application }}"
  - "{{ path_logs }}/{{ application }}"
  - "{{ path_runtime }}/{{ application }}"

- name: Create missing folders
  become: true
  file:
    dest: "{{ item['item'] }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  when: not item['stat']['exists'] | bool
  loop: "{{ folder_status.results }}"
