---
  # Configure firewall
- name: configure firewall settings
  become: true
  notify:
  - reload_daemon
  - restart_firewalld
  firewalld:
    permanent: yes
    state: enabled
    port: "{{ item }}"
  loop:
    - 4646-4648/tcp
    - 20000-32000/tcp
    - 4648/udp

- name: selinux permissive, logging actions that would be blocked
  become: true
  selinux:
    policy: targeted
    state: permissive
